title: Vincent Wu
description: The world needs automation and I am here to help!
show_downloads: false
google_analytics:
theme: jekyll-theme-leap-day
home: ./index.html
about: ./about.html
resume: https://drive.google.com/open?id=1w0nzg3tHEL7ek0NiIaQde8L3yOd3dYDv
linkedin: https://www.linkedin.com/in/vincentwu1998/
github_profile: https://github.com/VincentWu1998
github:
  repository_url: https://github.com/VincentWu1998/VincentWu1998.github.io